<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    /**
     * Seed vehicle listings for local/dev usage.
     */
    public function run(): void
    {
        $cars = [
            [
                'brand' => 'Toyota',
                'model' => 'Land Cruiser 300 ZX',
                'body_color' => 'Black',
                'body_type' => 'SUV',
                'doors' => 5,
                'seats' => 7,
                'title' => '2023 Toyota Land Cruiser 300',
                'slug' => '2023-toyota-land-cruiser-300',
                'year' => 2023,
                'location' => 'Dar es Salaam',
                'source_country' => 'Japan',
                'transmission' => 'Automatic',
                'fuel' => 'Diesel',
                'condition' => 'foreign_used',
                'import_status' => 'in_tanzania',
                'mileage_km' => 28000,
                'engine' => '3.3L Twin Turbo',
                'engine_capacity_cc' => 3300,
                'price_tzs' => 345000000,
                'landed_cost_tzs' => 358000000,
                'description' => 'Premium full-size SUV in excellent condition.',
                'is_featured' => true,
                'is_published' => true,
            ],
            [
                'brand' => 'Porsche',
                'model' => '911 Carrera',
                'body_color' => 'Racing Yellow',
                'body_type' => 'Coupe',
                'doors' => 2,
                'seats' => 4,
                'title' => '2021 Porsche 911 Carrera',
                'slug' => '2021-porsche-911-carrera',
                'year' => 2021,
                'location' => 'Arusha',
                'source_country' => 'Germany',
                'transmission' => 'Automatic',
                'fuel' => 'Petrol',
                'condition' => 'foreign_used',
                'import_status' => 'in_transit',
                'eta_date' => now()->addDays(45)->toDateString(),
                'mileage_km' => 18000,
                'engine' => '3.0L Turbo',
                'engine_capacity_cc' => 3000,
                'price_tzs' => 470000000,
                'landed_cost_tzs' => 498000000,
                'description' => 'Low mileage sports car with full service history.',
                'is_featured' => true,
                'is_published' => false,
            ],
            [
                'brand' => 'Ford',
                'model' => 'Ranger Raptor',
                'body_color' => 'Code Orange',
                'body_type' => 'Pickup',
                'doors' => 4,
                'seats' => 5,
                'title' => '2022 Ford Ranger Raptor',
                'slug' => '2022-ford-ranger-raptor',
                'year' => 2022,
                'location' => 'Dodoma',
                'source_country' => 'Thailand',
                'transmission' => 'Automatic',
                'fuel' => 'Diesel',
                'condition' => 'foreign_used',
                'import_status' => 'ready_for_booking',
                'mileage_km' => 46000,
                'engine' => '2.0L Bi-Turbo',
                'engine_capacity_cc' => 2000,
                'price_tzs' => 155000000,
                'landed_cost_tzs' => 164000000,
                'description' => 'Performance pickup built for rough terrain.',
                'is_featured' => false,
                'is_published' => true,
            ],
            [
                'brand' => 'Mercedes-Benz',
                'model' => 'G 63 AMG',
                'body_color' => 'Obsidian Black',
                'body_type' => 'SUV',
                'doors' => 5,
                'seats' => 5,
                'title' => '2020 Mercedes-AMG G 63',
                'slug' => '2020-mercedes-amg-g-63',
                'year' => 2020,
                'location' => 'Dar es Salaam',
                'source_country' => 'United Arab Emirates',
                'transmission' => 'Automatic',
                'fuel' => 'Petrol',
                'condition' => 'foreign_used',
                'import_status' => 'in_tanzania',
                'mileage_km' => 39000,
                'engine' => '4.0L V8 Biturbo',
                'engine_capacity_cc' => 4000,
                'price_tzs' => 620000000,
                'landed_cost_tzs' => 642000000,
                'description' => 'Luxury SUV with top trim and pristine interior.',
                'is_featured' => true,
                'is_published' => true,
            ],
            [
                'brand' => 'Nissan',
                'model' => 'Patrol LE',
                'body_color' => 'Pearl White',
                'body_type' => 'SUV',
                'doors' => 5,
                'seats' => 7,
                'title' => '2019 Nissan Patrol LE',
                'slug' => '2019-nissan-patrol-le',
                'year' => 2019,
                'location' => 'Mwanza',
                'source_country' => 'Japan',
                'transmission' => 'Automatic',
                'fuel' => 'Petrol',
                'condition' => 'local_used',
                'import_status' => 'in_tanzania',
                'mileage_km' => 74000,
                'engine' => '5.6L V8',
                'engine_capacity_cc' => 5600,
                'price_tzs' => 198000000,
                'landed_cost_tzs' => 205000000,
                'description' => 'Reliable family SUV with strong road presence.',
                'is_featured' => false,
                'is_published' => false,
            ],
            [
                'brand' => 'BMW',
                'model' => 'X5 xDrive40i',
                'body_color' => 'Alpine White',
                'body_type' => 'SUV',
                'doors' => 5,
                'seats' => 5,
                'title' => '2022 BMW X5 xDrive40i',
                'slug' => '2022-bmw-x5-xdrive40i',
                'year' => 2022,
                'location' => 'Zanzibar',
                'source_country' => 'Germany',
                'transmission' => 'Automatic',
                'fuel' => 'Petrol',
                'condition' => 'foreign_used',
                'import_status' => 'on_order',
                'eta_date' => now()->addDays(30)->toDateString(),
                'mileage_km' => 33000,
                'engine' => '3.0L Turbo',
                'engine_capacity_cc' => 3000,
                'price_tzs' => 255000000,
                'landed_cost_tzs' => 268000000,
                'description' => 'Executive SUV with balanced luxury and performance.',
                'is_featured' => false,
                'is_published' => true,
            ],
            [
                'brand' => 'Mazda',
                'model' => 'CX-5 AWD',
                'body_color' => 'Deep Crystal Blue',
                'body_type' => 'SUV',
                'doors' => 5,
                'seats' => 5,
                'title' => '2024 Mazda CX-5 AWD',
                'slug' => '2024-mazda-cx-5-awd-sample',
                'year' => 2024,
                'location' => 'Dar es Salaam',
                'source_country' => 'Japan',
                'transmission' => 'Automatic',
                'fuel' => 'Petrol',
                'condition' => 'foreign_used',
                'import_status' => 'ready_for_booking',
                'mileage_km' => 16000,
                'engine' => '2.5L',
                'engine_capacity_cc' => 2500,
                'price_tzs' => 112000000,
                'landed_cost_tzs' => 118000000,
                'description' => 'Popular mid-size SUV with comfort, safety, and efficient performance.',
                'is_featured' => false,
                'is_published' => true,
            ],
            [
                'brand' => 'Toyota',
                'model' => 'Hilux Double Cab',
                'body_color' => 'Silver',
                'body_type' => 'Pickup',
                'doors' => 4,
                'seats' => 5,
                'title' => '2021 Toyota Hilux Double Cab',
                'slug' => '2021-toyota-hilux-double-cab',
                'year' => 2021,
                'location' => 'Dar es Salaam',
                'source_country' => 'Thailand',
                'transmission' => 'Automatic',
                'fuel' => 'Diesel',
                'condition' => 'local_used',
                'import_status' => 'in_tanzania',
                'mileage_km' => 54000,
                'engine' => '2.8L Turbo Diesel',
                'engine_capacity_cc' => 2800,
                'price_tzs' => 98000000,
                'landed_cost_tzs' => 104000000,
                'description' => 'Reliable pickup for business and family use with strong resale value.',
                'is_featured' => false,
                'is_published' => true,
            ],
            [
                'brand' => 'Toyota',
                'model' => 'Prado TXL',
                'body_color' => 'White Pearl',
                'body_type' => 'SUV',
                'doors' => 5,
                'seats' => 7,
                'title' => '2020 Toyota Land Cruiser Prado TXL',
                'slug' => '2020-toyota-land-cruiser-prado-txl',
                'year' => 2020,
                'location' => 'Arusha',
                'source_country' => 'Japan',
                'transmission' => 'Automatic',
                'fuel' => 'Diesel',
                'condition' => 'foreign_used',
                'import_status' => 'in_transit',
                'eta_date' => now()->addDays(25)->toDateString(),
                'mileage_km' => 47000,
                'engine' => '2.8L Turbo Diesel',
                'engine_capacity_cc' => 2800,
                'price_tzs' => 162000000,
                'landed_cost_tzs' => 171000000,
                'description' => 'Comfortable 7-seater SUV ideal for long trips and city driving.',
                'is_featured' => true,
                'is_published' => true,
            ],
            [
                'brand' => 'Mitsubishi',
                'model' => 'Pajero Sport',
                'body_color' => 'Graphite Gray',
                'body_type' => 'SUV',
                'doors' => 5,
                'seats' => 7,
                'title' => '2019 Mitsubishi Pajero Sport',
                'slug' => '2019-mitsubishi-pajero-sport',
                'year' => 2019,
                'location' => 'Mwanza',
                'source_country' => 'Thailand',
                'transmission' => 'Automatic',
                'fuel' => 'Diesel',
                'condition' => 'local_used',
                'import_status' => 'in_tanzania',
                'mileage_km' => 69000,
                'engine' => '2.4L Turbo Diesel',
                'engine_capacity_cc' => 2400,
                'price_tzs' => 84000000,
                'landed_cost_tzs' => 89000000,
                'description' => 'Family SUV with practical features and dependable performance.',
                'is_featured' => false,
                'is_published' => true,
            ],
        ];

        foreach ($cars as $row) {
            Car::updateOrCreate(['slug' => $row['slug']], $row);
        }

        // Backfill older rows created before brand support.
        Car::query()
            ->where(function ($query): void {
                $query->whereNull('brand')->orWhere('brand', '');
            })
            ->whereNotNull('title')
            ->get()
            ->each(function (Car $car): void {
                $parts = preg_split('/\s+/', (string) $car->title);
                $guessedBrand = $parts[1] ?? null;
                if (is_string($guessedBrand) && $guessedBrand !== '') {
                    $car->brand = $guessedBrand;
                    $car->save();
                }
            });

        // Add larger synthetic volume only for non-production data environments.
        if (app()->environment(['local', 'staging', 'testing'])) {
            $target = 80;
            $missing = max(0, $target - Car::query()->count());
            if ($missing > 0) {
                Car::factory($missing)->create();
            }
        }
    }
}
